version: '3.8'

services:
  app:
    container_name: skk_tender_app
    build: .
    ports:
      - "3000:3000"
    volumes:
      # Tetap gunakan Bind Mount untuk database (ini berhasil)
      - ./database.db:/app/database.db 
      # Gunakan Named Volume untuk PDF (sesuai permintaan)
      - pdf_downloads:/app/src/download\ pdf 
    restart: unless-stopped
    # environment:
      # - NODE_ENV=production

# Definisikan named volume yang digunakan di atas
volumes:
  pdf_downloads: # Volume untuk menyimpan PDF yang diunduh oleh container

# Hapus definisi named volumes di bawah ini
# volumes:
#  db_data:
#  pdf_downloads: 